Added project of s22sprokate
karlis-i/PD1-2023r pull request #11
Opened 2023-10-26 18:30 UTC by s22sprokate

2023-10-27 09:40 UTC, karlis-i requested changes
Izskatās labi, bet varētu nedaudz uzlabot

2023-10-27 09:40 UTC, karlis-i commented on s22sprokate/index.html
> +        background-color: lightpink;
This goes into CSS file! :)

2023-10-27 09:40 UTC, karlis-i commented on s22sprokate/index.html
> +            <li> **Diet**: Maine Coon cats are large and active, so they need a well-balanced diet. Consult your veterinarian for recommended cat food and portion sizes.</li>
Jūs varat izmantot `::before` un `::after`, lai pievienotu zvaigznes, vai arī klases, lai citādi izceltu šos virsrakstus.
Un vispār, paskatieties, vai `<dl>` elements šeit nav vairāk piemērots- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

2023-10-27 09:40 UTC, karlis-i commented on s22sprokate/style.css
> +}
No kurienes šis resets?

2023-10-28 07:56 UTC, s22sprokate commented on s22sprokate/index.html
> +            <li> **Diet**: Maine Coon cats are large and active, so they need a well-balanced diet. Consult your veterinarian for recommended cat food and portion sizes.</li>
Palasiju par <dl>, bet nolēmu pagaidām vismaz atstāt savu variantu.

2023-10-31 19:23 UTC, karlis-i approved these changes

2023-10-31 19:24 UTC, merged