Added files for the project
karlis-i/PD1-2023r pull request #13
Opened 2023-10-27 07:32 UTC by matyssxdxd

2023-10-27 09:47 UTC, karlis-i requested changes
Izlabo emoji kodā, lūdzu!

2023-10-27 09:47 UTC, karlis-i commented on s22purvmati/index.html
> +              <th>🐱</th>
Šādi iekļaujot emodžus vari saskarties ar encoding kļūdām

2023-10-27 09:54 UTC, matyssxdxd commented on s22purvmati/index.html
> +              <th>🐱</th>
Skaidrs, iekš footer biju samainījis, bet te, laikam, palaidu garām...

2023-10-31 19:25 UTC, karlis-i approved these changes

2023-10-31 19:25 UTC, merged