Lara's First Project (2ITB-EN)
karlis-i/PD1-2023r pull request #14
Opened 2023-10-27 09:23 UTC by larabernardes

2023-10-27 09:58 UTC, karlis-i requested changes
Code looks impressive, but some things could be improved

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/aboutme.html
> +            alt="Picture of the creator"  title="This is me, Lara!" height = "800" width = "800" loading="lazy">
1) Dimensions should be set in CSS
2) For images, it's better to define width OR height, so that the browser can preserve proportions of images

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/aboutme.html
> +        <br>
It would be better to set margin-bottom for these paragraphs, not `<br>` !

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/aboutme.html
> +                        <td> <a class="TableStyle" href="extra/kittycat.png" download> CLICK FOR A SURPRISE! &#x2764;&#xFE0F; </a></td>
This is how people get viruses :D

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/index.html
> +        <p> Professor Kārlis Immers, autumn 2023, 2ITB-EN class </p>
I am not a professor, just a lecturer ;)

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/style/main.css
> +  content:"★";
Better use Unicode codes for these characters (just like with emojis in project description), otherwise you might experience encoding problems

2023-10-27 09:58 UTC, karlis-i commented on s22bernlara/style/main.css
> +  background-color: rgb(30, 39, 73);
Why both hsl and rgb? It would be better to stick to one format across the project

2023-10-27 11:38 UTC, larabernardes commented
All the fixes requested have been made. :)

2023-10-31 19:29 UTC, karlis-i commented on s22bernlara/aboutme.html
> +                        <td> <a class="TableStyle" href="extra/kittycat.png" download> CLICK FOR A SURPRISE! &#x2764;&#xFE0F; </a></td>
Email and phone number weren't the problem, just the "click here for a surprise" part :)

2023-10-31 19:38 UTC, karlis-i commented on s22bernlara/style/main.css
> +  background-color: rgb(30, 39, 73);
I appreciate that you've set all colors to HSL format now, but it's used very rarely, I haven't ever seen it used.
You don't have to change it- if it works, it works! Just keep in mind that most web developers and designers usually use HEX format- `#daa520` for 'goldenrod', `#fff` for 'white' and so on. (And RGBA format for when you need opacity)

2023-10-31 19:39 UTC, karlis-i approved these changes

2023-10-31 19:39 UTC, merged

2023-10-31 19:47 UTC, larabernardes commented on s22bernlara/aboutme.html
> +                        <td> <a class="TableStyle" href="extra/kittycat.png" download> CLICK FOR A SURPRISE! &#x2764;&#xFE0F; </a></td>
Haha, I won't ever use this function like that in any professional work, I promise. It was just a joke. I even considered naming the kitten "Trojan," but it would have been too bold of me! :´)

2023-10-31 19:48 UTC, larabernardes commented on s22bernlara/style/main.css
> +  background-color: rgb(30, 39, 73);
Noted, thank you!