S22kalndani
karlis-i/PD1-2023r pull request #17
Opened 2023-11-02 17:16 UTC by Slinkyss

Fixed previous pull request issues and added 1 new form. Also did not know how to fix the last pull request so i just made a new one

2023-11-06 20:21 UTC, karlis-i requested changes
Neizmantots fonta imports, un CSS kodā ir daudz krāsu vērtības, ko, iespējams, varētu pāŗvietot uz mainīgajiem.
Lai labojumi parādītos šajā pull request'ā, vienkārši jāpush'o izmaiņas uz Github

2023-11-06 20:21 UTC, karlis-i commented on s22kalndani/index.html
> +        <link href="https://fonts.googleapis.com/css2?family=Grandstander:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
Joprojām tiek iekļauts Grandstander fonts, bet nekur netiek izmantots

2023-11-10 09:13 UTC, Slinkyss commented
I did push the fix. But it does not show here the changes?

2024-01-11 17:51 UTC, karlis-i approved these changes

2024-01-11 17:51 UTC, merged