Added EndijsBertans PD1
karlis-i/PD1-2023r pull request #3
Opened 2023-10-25 16:48 UTC by endijsbertans

2023-10-26 08:14 UTC, endijsbertans commented
https://endijsbertans.github.io/HTMLprojecc/

2023-10-26 17:59 UTC, karlis-i commented
Kādēļ divi CSS faili?
Izskatās, ka neesi pievienojis saiti studentu sarakstā

2023-10-26 18:01 UTC, karlis-i requested changes
Kādēļ divi CSS faili?
Izskatās, ka neesi pievienojis saiti studentu sarakstā

2023-10-31 18:57 UTC, karlis-i approved these changes

2023-10-31 18:57 UTC, merged