add Annijas Aumales project
karlis-i/PD1-2023r pull request #47
Opened 2024-01-11 22:48 UTC by skog03

2024-01-12 10:31 UTC, karlis-i requested changes
Izskatās, ka visi HTML faili ir dublēti arī ārpus Jūsu direktorijas- tos derētu izdzēst

2024-01-12 15:10 UTC, karlis-i commented
Kā izlabot-
1. pārslēdzamies uz master zaru ar komandu `git checkout master`
2. nokopē studentu saraksta index.html failu kaut kur savā datorā
3. pārslēdzies atpakaļ savā zarā ar komandu `git checkout s22aumaanni`
4. pārvieto nokopēto index.html failu atpakaļ tā vietā- blakus s22aumaanni direktorijai
5. nosūti izmaiņas uz Github ar komandām `git add`, `git commit` un `git push`

2024-01-12 19:50 UTC, skog03 commented
ak dievs, es atvainojos, ka tā. bija dažas problēmas ielikt atpakaļ, taču tagad cerams, ka viss labi

2024-01-13 10:01 UTC, karlis-i approved these changes

2024-01-13 10:01 UTC, merged