Submission of PD1
karlis-i/PD1-2023r pull request #6
Opened 2023-10-26 16:21 UTC by KristiansKokars

hopefully I won't need any more changes here

2023-10-26 18:09 UTC, karlis-i requested changes
Derētu daži labojumi

2023-10-26 18:09 UTC, karlis-i commented on index.html
> +                                <a href="./kristians.kokars/index.html">&#x1F431; Kristiāns Kokars &#x1F431</a>
Tur nepietrūkst semikols?

2023-10-26 18:09 UTC, karlis-i commented on kristians.kokars/index.html
> +    <link rel="stylesheet" href="css/reset.css">
Labi, ka zini par Tailwind, bet šajā darbā labāk resetu uzraksti pats!

2023-10-26 18:09 UTC, karlis-i commented on kristians.kokars/index.html
> +        <img src="img/dungeonsandcats.jpg" width="200" height="200" alt="Dungeons and Cats">
ja izmantojam vienu failu, no source set īsti nav jēgas

2023-10-27 07:20 UTC, KristiansKokars commented on kristians.kokars/index.html
> +    <link rel="stylesheet" href="css/reset.css">
Ar cieņu, es neredzu jēgu rakstīt reset CSS pašam - tas būtu tas pats kas ir šeit (reset loģika nemainās), bet izlikties ka ir paša rakstītais un bez komentāriem vai atsauces, kas jūtas nepareizi

2023-10-27 07:21 UTC, KristiansKokars commented on kristians.kokars/index.html
> +        <img src="img/dungeonsandcats.jpg" width="200" height="200" alt="Dungeons and Cats">
Es biju pielietojis to lai nomainītu fixed lielumu uz maziem ekrāniem, citādāk bilde iziet no skata - vai ir labāks atrisinājums tai problēmai?

2023-10-31 18:58 UTC, karlis-i commented on kristians.kokars/index.html
> +        <img src="img/dungeonsandcats.jpg" width="200" height="200" alt="Dungeons and Cats">
Jā- CSS

2023-10-31 18:58 UTC, karlis-i commented on kristians.kokars/index.html
> +    <link rel="stylesheet" href="css/reset.css">
ok

2023-11-06 19:58 UTC, karlis-i approved these changes

2023-11-06 20:02 UTC, karlis-i commented
Apstiprinu, bet vari uzlabot, ja vēlies- Tev visām bildēm norādīti `width` un `height` atribūti, būtu labāk, ja bilžu izmērus norādītu ar CSS, turklāt, parasti norāda tikai vienu no izmēriem- tādā veidā pārlūks var aprēķināt otru, saglabājot attēlu proporcijas

2023-11-06 20:02 UTC, merged